# Generated by Django 3.2.6 on 2022-01-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220106_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todo.todocollection'),
        ),
    ]
