# Generated by Django 3.2.6 on 2022-01-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todo.todocollection'),
            preserve_default=False,
        ),
    ]
